import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

public class DiamondBlockPlugin extends JavaPlugin {

    @Override
    public void onEnable() {
        // 插件启动时的初始化代码
    }

    @Override
    public void onDisable() {
        // 插件关闭时的清理代码
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("giveDiamondBlock")) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                player.getInventory().addItem(new ItemStack(Material.DIAMOND_BLOCK, 1));
                player.sendMessage("你获得了一个钻石方块!");
                return true;
            }
        }
        return false;
    }
}
